# Generated by Django 2.2.6 on 2019-10-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='static/def.png', upload_to='post_picture'),
        ),
    ]
