# Generated by Django 2.2.6 on 2019-10-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_session_sessionslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
